# -*- coding: utf-8 -*-
"""WebScrapping - FBREF.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tyrlzgQFtdSNxcRDECdBeRZ_lqd-x4NA
"""

!pip install requests
!pip install beautifulsoup4
!pip install html5lib

!pip install xlsxwriter

!pip install openpyxl

!pip install pandas

!pip install xlrd

!pip install json-lines
