# -*- coding: utf-8 -*-
"""Futebol_BR_22.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Yt7QTUmP_-qDXM6EN1Bo6sk42rnMS2n-
"""

!pip install google-cloud-storage

!pip install google-auth

!pip install requests

!pip install google-api-python-client

!pip install jsonschema

!pip install pandas

!pip install --upgrade pandas
