# -*- coding: utf-8 -*-
"""Estatistica v1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IHtswTCYg8SZry9nsIzxwc1EFsqojeCt

Cotovelo
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
import numpy as np

# Montar o Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Especifique o caminho completo para o seu arquivo no Google Drive
file_path = '/content/drive/MyDrive/Futebol/Dados/Fut 1.2 - Quintil.xlsx'

# Lista de posições e suas respectivas colunas
posicoes = {
    'Goleiros': ['goals.conceded', 'goals.saves', 'passes.on', 'duels.won', 'penalty.saved'],
    'Zagueiros': ['passes.on', 'tackles', 'blocks', 'interceptions', 'duels.won', 'duels.total'],
    'Laterais': ['passes.key', 'passes.on', 'tackles', 'blocks', 'interceptions', 'duels.won', 'dribbles.success'],
    'Volantes': ['passes.key', 'passes.on', 'tackles', 'blocks', 'interceptions', 'duels.won', 'dribbles.success'],
    'Meio Ofensivos': ['shots.on', 'goals.total', 'goals.assists', 'passes.key', 'passes.on', 'tackles', 'interceptions', 'duels.won', 'dribbles.success', 'fouls.drawn'],
    'Pontas': ['shots.on', 'goals.total', 'goals.assists', 'passes.key', 'passes.on', 'tackles', 'interceptions', 'duels.won', 'dribbles.success', 'fouls.drawn'],
    'Atacantes': ['shots.on', 'goals.total', 'goals.assists', 'passes.key', 'passes.on', 'tackles', 'interceptions', 'duels.won', 'dribbles.success']
}
